import { NutritionTargets, WeightGoal } from "@/features/authentication/types";
import {
  Food,
  FoodNutrients,
  CompatiblePlans,
  FoodType,
} from "@/features/foods/types";
import { Progress } from "@/features/progress";

export const DEFAULT_IMAGE = "/images/foods/default_food.png";

// Food
export const NewFoodType: FoodType = {
  is_breakfast: false,
  is_dinner: false,
  is_lunch: false,
  is_snack: false,
};

export const NewFoodCompatiblePlans: CompatiblePlans = {
  balanced: false,
  gluten_free: false,
  low_carb: false,
  mediterranean: false,
  vegetarian: false,
};

export const NewFoodNutrients: FoodNutrients = {
  betaine: null,
  caffeine: null,
  calcium: null,
  calories: null,
  carbohydrates: null,
  cholesterol: null,
  choline: null,
  copper: null,
  fats: null,
  fiber: null,
  fluoride: null,
  folate: null,
  fructose: null,
  galactose: null,
  glucose: null,
  iron: null,
  lactose: null,
  lycopene: null,
  magnesium: null,
  maltose: null,
  manganese: null,
  monounsaturated_fats: null,
  niacin: null,
  phosphorus: null,
  polyunsaturated_fats: null,
  potassium: null,
  proteins: null,
  retinol: null,
  saturated_fats: null,
  selenium: null,
  sodium: null,
  sucrose: null,
  sugar: null,
  thiamine: null,
  total_omega_3: null,
  total_omega_6: null,
  trans_fats: null,
  vitamin_a: null,
  vitamin_b12: null,
  vitamin_b2: null,
  vitamin_b6: null,
  vitamin_c: null,
  vitamin_d: null,
  vitamin_d2: null,
  vitamin_d3: null,
  vitamin_e: null,
  vitamin_k: null,
  water: null,
  zinc: null,
};

export const NewFood: Food = {
  allow_public: true,
  brand: null,
  compatible_plans: NewFoodCompatiblePlans,
  complexity: 1,
  cook_time: 0,
  curated: false,
  date_created: null,
  date_updated: null,
  diet_id: null,
  diet_meal_id: null,
  digestion_status: null,
  dish_type: null,
  easily_single_serving: false,
  eaten: false,
  food_category: null,
  food_description: null,
  food_id: null,
  food_name_lowercase: "",
  food_name: null,
  food_type: NewFoodType,
  glucemic_status: null,
  image: DEFAULT_IMAGE,
  index: -1,
  ingredients: {},
  instructions: [],
  is_deleted: false,
  kind: null,
  major_ingredients: null,
  makes_leftovers: false,
  note: "",
  num_dislikes: 0,
  num_favorites: 0,
  is_recommended: false,
  num_ingredients: 0,
  num_likes: 0,
  nutrients: NewFoodNutrients,
  order: -1,
  prep_time: 0,
  price: null,
  recipe_category: null,
  scale_amount: 0,
  scale_name: "",
  scales: [],
  serving_amount_per_package: null,
  serving_amount: 1,
  serving_grams: 0,
  serving_name: "Serving",
  source: null,
  total_time: 0,
  uploader_id: null,
};

export let FoodKeys = {} as Food;
Object.keys(NewFood).forEach((key: string) => {
  FoodKeys[key] = key;
});
