import { MeasurementUnits, UserAccount } from "@/types/types";

export const newAccount: UserAccount = {
  activity: null,
  age: null,
  BMI: null,
  BMR: null,
  created_at: "",
  display_name: "",
  email_address: "",
  food_preferences: [],
  gender: null,
  goal: null,
  height_in_cm: null,
  is_premium: false,
  is_profile_completed: false,
  kcals_recommended: null,
  lang: "",
  measurement_unit: null,
  photo_url: "",
  plan_selected: null,
  premium_plan: null,
  user_id: "",
  weight_goal_in_kg: null,
  weight_in_kg: null,
};
