export enum AppRoutes {
  create_diet = "/app/create/diet",
  create_food = "/app/create/food",
  create_meal = "/app/create/meal",
  create_recipe = "/app/create/recipe",
  create_user = "/app/create",
  favorites_foods = "/app/favorites",
  favorites_meals = "/app/favorites/meals",
  favorites_plans = "/app/favorites/plans",
  login = "/login",
  nav_menu = "/app/nav-menu",
  profile = "/app/profile",
  search_foods = "/app/search",
  search_my_creations = "/app/search/my-creations",
  shopping = "/app/shopping/today",
  signup = "/signup",
  today = "/app/today",
}
